### ISSUE TITLE
generateClient Fails when Query isn't named Query

### ISSUE THREAD

**Issue by jplabadie** [deweyjose/graphqlcodegen#30]
First, thanks for bringing this to Maven, my team and I appreciate it.

I'm new to graphQL, graphqlcodegen, and DGS in general, so my apologies if this is a stupid question.

I'm currently using this maven plugin in a project and failing to have client code generated unless I edit the schema. This is my configuration and a sample of the lines involved in the schema:

```
<plugin>
		<groupId>io.github.deweyjose</groupId>
		<artifactId>graphqlcodegen-maven-plugin</artifactId>
		<version>1.16</version>
		<executions>
			<execution>
				<goals>
					<goal>generate</goal>
				</goals>
			</execution>
		</executions>
		<configuration>
			<outputDir>${project.build.directory}/generated-sources/gql-sources</outputDir>
			<exampleOutputDir>${project.build.directory}/generated-examples/gql-examples</exampleOutputDir>
			<generateClient>true</generateClient>
			<generateBoxedTypes>true</generateBoxedTypes>
			<generateDataTypes>true</generateDataTypes>
			<writeToFiles>true</writeToFiles>
			<maxProjectionDepth>2</maxProjectionDepth>
			<typeMapping>
				<customerEffectiveDate>java.time.LocalDate</customerEffectiveDate>
				<customerEndDate>java.time.LocalDate</customerEndDate>
			</typeMapping>
			<schemaPaths>
				<param>src/main/resources/schema/graphqlapi.graphqls</param>
			</schemaPaths>
			<packageName>org.myapp.generated</packageName>
		</configuration>
</plugin>
```
			
```
schema {
  query: QueryRoot
}

...

type QueryRoot {
  customers(id: String, emailAlias: String, phoneNumber: String): [Customer]
  bookOfTheDead(bookId: String, bookCode: String): BookOfTheDead
}
```

If I refactor "QueryRoot" to "Query" in the schema, the client codegen suddenly notices the queries and generates all the expected Query and Projection classes as expected. Is the Schema I'm using non-standard? Am I missing a feature in the plugin, or is this really a bug?

**Comment by zorglube** [comment]
You schema seems bad. AS far as I know it might look like this : 
`
 type Something {
  query: QueryRoot
}

type QeryRoot [
 ... 
}

type Query {
  customers(id: String, emailAlias: String, phoneNumber: String): [Customer]
  bookOfTheDead(bookId: String, bookCode: String): BookOfTheDead
}
`

**Comment by deweyjose** [comment]
Hi @jplabadie. Glad you find the plugin useful! 

This is expected behavior. The maven plugin is a thin wrapper over the Netflix codegen library (same library their gradle plugin uses) which does have a requirement on the root types - they need to be  Query, Mutation and Subscription.

Let us know if there are any other questions.

**Comment by zorglube** [comment]
Query, Mutation ans Suscription aren't Netflix DGS requirements, it's
GraphQL requirements.

/----------------------/
BCRM : Dirigeant
Ingénieur EFREI : École FRançaise d'Électronique et d'Informatique
GSM : +33.(0)6.15.86.41.71

Waze : Éditeur, Area Manager Île de France
Solidarité Sida : bénévole

Envoyé depuis mon téléphone mobile.


Le mer. 26 janv. 2022 à 15:04, deweyjose ***@***.***> a
écrit :

**Comment by jplabadie** [comment]
@zorglube @deweyjose 

Thank you, and hearing that is the standard really helps. I consider this closed.

**Comment by deweyjose** [comment]
@jplabadie @zorglube  just wanted to follow up here to avoid some confusion.

What you had is a perfectly valid graphql schema. I work with some teams that use something similar using schema to setup query/mutation and mapping query to something like `type RootQueryType` that defines all of the queries for that particular schema. DGS can generate types for that and run that schema if you're using Java and the rest of the server side libraries they provide.

The problem is generating the client code - the codegen plugin will not generate `client` code and projections as you noticed unless the type is `Query` or  `Mutation`. Even if you've specified in the schema {} block what query and mutation  types are. 


This schema is powered by DGS Java based server - you can see RootQueryType is defined here, not Query, and executed the shows query.

<img width="1440" alt="Screen Shot 2022-01-26 at 11 32 09 AM" src="https://user-images.githubusercontent.com/15958124/151206874-e1f57f3f-b2d7-49ec-a783-108c10630559.png">

Here you can see codegen did not generate client code or shows, or any other field on RootQueryType, but did generate code for createShow.

<img width="460" alt="Screen Shot 2022-01-26 at 11 32 22 AM" src="https://user-images.githubusercontent.com/15958124/151207361-edc42dbe-eca9-4894-803b-108d41953751.png">

If we rename RootQueryType to Query in this example DGS codegen will generate code for shows and bars.

If there was any confusion I hope this cleared it up.

**Comment by deweyjose** [comment]
> Query, Mutation and Suscription aren't Netflix DGS requirements, it's a GraphQL requirements.

Not exactly - You can map other types to query, mutation in the schema {} definition block. Perfectly valid as in @jplabadie example. The issue is - `client` DGS codegen only supports types named `Query`, `Mutation` and `Subscription` in my experience.

**Comment by jplabadie** [comment]
Yes this is pretty clear. It's simply a convention, not a requirement of GraphQL, but because the schema is pretty sparse syntactically the codegen authors had to make some assumptions about where their plugin could search for Queries, Mutations, and Subscriptions.

Thanks again!
