### ISSUE TITLE
Plugin delete existing files in <outputDir> 

### ISSUE THREAD

**Issue by MinkaReZ** [deweyjose/graphqlcodegen#35]
Hi,
In my project where is already one code generation plugin (`apt-maven-plugin` which generates code for QueryDSL framework at `target/generated-sources/java`)
When i added `graphqlcodegen-maven-plugin` i see that it successful generate code at `target/generated-sources`, but code for QueryDsl now is missing.
Both plugins execute at `generate-sources` maven phase, but from console output i see that `graphqlcodegen-maven-plugin` executes after `apt-maven-plugin`. So I purpose that it implicitly clear `target/generated-sources` folder before self code generation.

As workaround i change `outputDir` for `graphqlcodegen-maven-plugin` and was forced to add one more folder for source code at `build-helper-maven-plugin`

It will be nice if you change this behavior and plugin won't delete existing files in `outputDir`

Thank you.

**Comment by deweyjose** [comment]
Hi @MinkaReZ this plugin is a thin wrapper over the Netflix DGS codegen library. It doesn't delete any of the output folders. I also took a look at the underlying codegen library [here](https://github.com/Netflix/dgs-codegen/blob/master/graphql-dgs-codegen-core/src/main/kotlin/com/netflix/graphql/dgs/codegen/CodeGen.kt) and didn't see any code that's explicitly deleting files.

I tried to reproduce locally with version 1.21 of this plugin without success by adding a package and test file under the `target/generated-sources` folder. Subsequent invocations of this plugin did not delete my test package under `target/generated-sources`. 

Could you try upgrading to the latest version of this plugin (1.21) or provide more of pom files to see if we can help figure out what the issue is?
